############# Chinese navigation ##############

# main menu
[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "关于"
url = "about/"
weight = 2
hasChildren = true

  [[main]]
  parent = "关于"
  name = "什么是WFST？"
  url = "https://gethugothemes.com/"
  weight = 1

  [[main]]
  parent = "关于"
  name = "望远镜"
  url = "project/"
  weight = 2

  [[main]]
  parent = "关于"
  name = "台址"
  url = "project/"
  weight = 3

  [[main]]
  parent = "关于"
  name = "相机"
  url = "project/"
  weight = 4

  [[main]]
  parent = "关于"
  name = "团队"
  url = "project/"
  weight = 5

[[main]]
name = "科学"
url = "project/"
weight = 3
hasChildren = true

  [[main]]
  parent ="科学" 
  name = "时域科学"
  url = "project/"
  weight = 1
  

  [[main]]
  parent = "科学"
  name = "太阳系天体"
  url = "project/"
  weight = 2
  

  [[main]]
  parent = "科学"
  name = "银河系及卫星星系"
  weight = 3
  url = "project/"

  [[main]]
  parent = "科学"
  name = "星系形成演化与宇宙学"
  weight = 4
  url = "project/"

[[main]]
name = "巡天及数据"
url = "blog/"
weight = 4
hasChildren = true

  [[main]]
  parent = "巡天及数据"
  name = "巡天策略及计划"
  weight = 1
  url = "project/"

  [[main]]
  parent = "巡天及数据"
  name = "数据处理及管理"
  weight = 2
  url = "project/"
  
  [[main]]
  parent = "巡天及数据"
  name = "Alert stream"
  weight = 3
  url = "project/"

    [[main]]
  parent = "巡天及数据"
  name = "数据释放"
  weight = 4
  url = "project/"

  
[[main]]
weight = 5
name = "出版"
hasChildren = true

  [[main]]
  parent = "出版"
  name = "出版"
  url = "project/"
  weight = 1
  
  [[main]]
  parent = "出版"
  name = "亮点研究"
  url = "project/"
  weight = 2

[[main]]
weight = 6
name = "新闻及会议"
hasChildren = true

  [[main]]
  parent = "新闻及会议"
  name = "新闻"
  url = "project/"
  weight = 1

  [[main]]
  parent = "新闻及会议"
  name = "会议"
  url = "project/"
  weight = 2

[[main]]
weight = 7
name = "教育及outreach"
hasChildren = true

  [[main]]
  parent = "教育及outreach"
  name = "教育"
  url = "project/"
  weight = 1

  [[main]]
  parent = "教育及outreach"
  name = "多媒体"
  url = "project/"
  weight = 2


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Project"
url = "project/"
weight = 3

[[footer]]
name = "Service"
url = "service/"
weight = 4

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7